### ISSUE TITLE
Not Found on first render

### ISSUE THREAD

**Issue by micahstubbs** [nickretallack/nameless-reason#1]
so, on first render all I see on the page is the text `Not Found`.  

to get here, I followed the instructions in the README https://github.com/nickretallack/nameless-reason#nameless-reason

@nickretallack curious, is this the expected behavior? what am I missing?

![screen shot 2018-09-11 at 9 30 06 pm](https://user-images.githubusercontent.com/2119400/45402320-ebb0e600-b609-11e8-8588-991ee3c43892.png)

**Comment by nickretallack** [comment]
Known but not intended.  The graph definitions that currently exist in this version are:

- example: A function that contains three recursive calls of itself where one is dead code, for testing layout
- simple: 1 + 1
- point-example: Constructs and destructures an algebraic data type
- reference-example: Returns a reference

You can navigate to them by putting those names in the fragment identifier at the end the URL, like so:

`#example`

It was supposed to default to "example" but I messed up.  Btw, in the future these names won't be readable but will be long random strings.  This project is a really early-stage port of [my visual language](nickretallack.com/visual_language/#/ace0c51e4ee3f9d7483ec10780d1ed43) to ReasonReact.  Thanks for expressing interest!

**Comment by nickretallack** [comment]
I've added an index page so you can more easily discover the definitions.
